name: Cancel
on:
  workflow_run:
    workflows:
    - '*'
jobs:
   cancel:
     runs-on: ubuntu-latest
     steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.workflow_run.head_repository) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
         workflow_id: ${{ github.event.workflow.id }}
